# Generated by Django 3.2.7 on 2021-10-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('bus_route_id', models.IntegerField()),
                ('bus_route_number', models.CharField(max_length=100)),
                ('bus_route_name', models.CharField(max_length=200)),
                ('bus_station_count', models.IntegerField()),
                ('bus_route_length', models.IntegerField()),
                ('bus_transferability', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=5000)),
                ('start_node_id', models.CharField(max_length=5000)),
                ('end_node_id', models.CharField(max_length=5000)),
                ('road_name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RoadNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=5000)),
                ('node_name', models.CharField(max_length=500)),
                ('rlatitude', models.FloatField()),
                ('rlongitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StationUsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.CharField(max_length=5000)),
                ('day_of_week', models.CharField(max_length=5000)),
                ('base_hour', models.IntegerField()),
                ('bus_station_id', models.IntegerField()),
                ('bus_station_name', models.CharField(max_length=5000)),
                ('get_on_off_type', models.CharField(max_length=300)),
                ('user_count', models.IntegerField()),
            ],
        ),
    ]
