version: '3.1'

services:

  db:
    image: postgres:10.19-alpine
    restart: always
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"