[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.github
  | README.md
  | Pipfile
  | Pipfile.lock
  | Bus_backend
)/
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
skip_glob = "*/migrations/*"
force_single_line = true
