name: test

on : push

jobs:
  bulid:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.16
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.10'

      - name: Cache python packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install pipenv
          pipenv install --dev --ignore-pipfile
          pipenv --venv
